alias: 'Rob away'
initial_state: 'on'
trigger:
  - platform: numeric_state
    entity_id: proximity.person2_home
    above: 400
  - platform: state
    entity_id: 
      - device_tracker.40_4e_36_24_53_15
      - device_tracker.person2_bt_mobile
      - device_tracker.person2_bt_front_mobile
    to: 'not_home'
  - platform: homeassistant
    event: start
condition:
  # currently home
  - condition: state
    entity_id: input_boolean.person2_home
    state: 'on'
  # As long as at least two trackers mark as away, they're away
  - condition: numeric_state
    entity_id: group.person_person2
    below: 2
    value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_person2', 'entity_id'))|list)|groupby('state'))['home']|count }}"
  # Either a door just opened/closed, or we're far, far away
  - condition: or
    conditions:
    # An exit door recently opened or closed, or motion in the vestibule
    - condition: template
      value_template: >-
        {{ ((as_timestamp(now()) - as_timestamp(states.binary_sensor.pi3_front_door_sensor.last_updated)) | int < 300) 
          or 
           ((as_timestamp(now()) - as_timestamp(states.binary_sensor.pi3_garage_closed_car_sensor.last_updated)) | int < 300) 
          or
           ((as_timestamp(now()) - as_timestamp(states.binary_sensor.vestibule_occupancy.last_updated)) | int < 300) 
        }}
    # All away, and not near
    - condition: and
      conditions:
      - condition: state
        entity_id: group.person_person2
        state: 'not_home'
      - condition: numeric_state
        entity_id: proximity.person2_home
        above: 400
action:
  - service: script.person2_away
